Override transferOwnership in API3 token
api3dao/api3-contracts pull request #13
Opened 2020-10-09 02:06 UTC by rare13

Updates the transferOwnership function to ensure when owners are removed, their minting permissions are also removed. Also automatically gives the new owner minting permissions as this saves them from sending a transaction to set this.

2020-10-09 07:20 UTC, bbenligiray commented
Ownership and minting authority are independent. We don't want to give minting permission to no one who doesn't need it, including the owner.

The DAO will be keeping the ownership of the token at all times. If we give minting authority to the DAO, that means we're one proposal away from someone minting a huge amount of tokens for themselves (vs. 2). Since there is no mechanism that will require the DAO to mint tokens directly, I don't think that we need this to be done this easily.

The minting authority is supposed to be given to contracts with an immutable schedule/logic that wouldn't have these kind of risks (assuming they are implemented correctly). For example, InflationManager plugs into the staking pool and mints inflationary rewards. The DAO would give minting authority to this contract:
https://github.com/api3dao/api3-contracts/blob/6d43fa85fb7ec9f84e18b5e86b2fdcea5eb6ddf9/packages/api3-pool/contracts/InflationManager.sol#L96-L114

2020-10-09 07:26 UTC, bbenligiray commented
Maybe we can only revoke minting authority from the previous owner (in case it has it), but not give it to the new owner. I don't see much point though.

2020-10-11 04:10 UTC, rare13 commented
@bbenligiray that makes sense to not give minting power to the owner by default. I'll edit the PR to just revoke minting authority from the previous owner, just as a fail safe for ownership transfer. Imo its still worth having this as it just provides an extra level of protection when moving, but agree on keeping the ownership vs minting concerns separated.

2020-10-11 11:16 UTC, bbenligiray requested changes
Can you also add the `@param` line to your docstrings and add the method to the interface?

2020-10-11 11:16 UTC, bbenligiray commented on packages/api3-token/contracts/Api3Token.sol
> +        public
```suggestion
        external
```

2020-10-11 11:16 UTC, bbenligiray commented on packages/api3-token/test/Api3Token.sol.js
> +        .withArgs(roles.randomPerson._address, true);
Fails otherwise

2020-10-14 08:54 UTC, merged